### PR TITLE
Don't include in release files not needed in it

### PR DESCRIPTION
**Pull request by kubawerlos**

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Thank you for your contribution. I appreciate the time you invested in preparing this pull request. However, I have decided not to merge it.

**Comment by kubawerlos** [comment]
@sebastianbergmann what's the reasoning? Why any of these files should be in release?

**Comment by kubawerlos** [comment]
@sebastianbergmann what's the reasoning? Why any of these files should be in release?

**Comment by sebastianbergmann** [comment]
OS package maintainers such as @remicollet need the archives that GitHub creates for tags to contain tests, etc. If we `export-ignore` tests then they will not be part of these archives.

**Comment by kubawerlos** [comment]
Need for what? I'm trying to understand. I've always believed we don't need tests in archive ever, e.g. Guzzle does that: https://github.com/guzzle/guzzle/blob/6.5.2/.gitattributes#L12

Even if someone needs it there is always `--prefer-source` flag in Composer.

**Comment by sebastianbergmann** [comment]
@remicollet uses the archives to run the tests. For that to work the tests need to be in the archive.

**Comment by kubawerlos** [comment]
Is it public, somewhere?

Can we remove the entries:
```
/tests/      export-ignore
/phpunit.xml export-ignore
```

and go ahead with others?

**Pull request closed without merging**
